name: awesome_weather
description: "Awesome Weather mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^8.0.2
  injectable: ^2.6.0
  dio: ^5.9.0
  envied: ^1.3.1
  flutter_svg: ^2.2.2
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  flutter_timezone: ^5.0.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.12.0
  hive_ce_generator: ^1.8.2
  test: ^1.26.2
  test_api: ^0.7.6
  bloc_test: ^10.0.0
  mockito: ^5.5.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

